### ISSUE TITLE
Can you give the tran.txt file or a specific description about it?

### ISSUE THREAD

**Issue by Martinser** [implus/UM-MAE#1]
[17:17:52.401794] using regular, mask_candidate shape =  (128, 4)
[17:17:52.401841] load info from /home/UM-MAE-main/path/to/ImageNet/train.txt
Traceback (most recent call last):
  File "main_pretrain.py", line 247, in <module>
    main(args)
  File "main_pretrain.py", line 139, in main
    dataset_train = ImageListFolder(train_folder, transform=transform_train, ann_file=train_ann_file)
  File "/home/UM-MAE-main/util/datasets.py", line 32, in __init__
    ann = open(ann_file)
FileNotFoundError: [Errno 2] No such file or directory: '/home/UM-MAE-main/path/to/ImageNet/train.txt'

**Comment by implus** [comment]
Please refer to IN1K/train.txt and IN1K/val.txt. Move them to your imagenet root path.
